### ISSUE TITLE
markdown短代码不兼容

### ISSUE THREAD

**Issue by xulouzhe** [trinitrotofu/Bubble#10]
先给新版本点一个赞。
我编辑文章用的是markdown的编辑器插件Editor.md，发现不兼容新版本的短代码功能（启用编辑器就不解析bbcode），想问一下有没有解决方法，还是换回自带编辑器。

**Comment by xulouzhe** [comment]
插件链接 https://github.com/DT27/EditorMD

**Comment by trinitrotofu** [comment]
@xulouzhe 很抱歉回复晚了。

> 启用后将使用 marked.js 接管前台 Markdown 解析，但接管前台解析后，会导致与文章内容有关的插件失效。

这是该插件的一段说明。

bbcode 实际上就是通过一个 JS 代码寻找 bbcode 标签并进行内容的替换，您也可以将其理解为一个插件。

因此建议您换回 Typecho 自带编辑器，我个人认为自带编辑器很好用了（个人观点）。

**Comment by xulouzhe** [comment]
好的，谢谢
