### ISSUE TITLE
不兼容reCAPTCHA

### ISSUE THREAD

**Issue by 66Leo66** [trinitrotofu/Bubble#16]
在comments.php约107行插入了[reCAPTCHA插件](https://github.com/typecho-fans/plugins/tree/master/reCAPTCHA)的php代码`<?php reCAPTCHA_Plugin::output(); ?>`，在未完成reCAPTCHA验证的情况下仍然可以发表评论。

**Comment by 66Leo66** [comment]
在使用Single主题的时候reCAPTCHA是正常的。

**Comment by trinitrotofu** [comment]
@66Leo66 经测试在我的站点上该插件可正常工作。
请注意登陆后验证码不输入也是可以正常评论的，请推出登陆后测试该功能。

**Comment by 66Leo66** [comment]
好像是这么回事，ok了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TriNitroTofu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月25日(星期六) 晚上8:11
收件人:&nbsp;"trinitrotofu/Bubble"<Bubble@noreply.github.com&gt;;
抄送:&nbsp;"66Leo66"<1463359949@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [trinitrotofu/Bubble] 不兼容reCAPTCHA (#16)





 
@66Leo66 经测试在我的站点上该插件可正常工作。
 请注意登陆后验证码不输入也是可以正常评论的，请推出登陆后测试该功能。
