### ISSUE TITLE
分类显示Bug

### ISSUE THREAD

**Issue by xulouzhe** [trinitrotofu/Bubble#2]
后台增加了多个分类。文章设置了某几个分类。但是实际上还是会显示所有分类。
举例：
1. 有A、B、C三个分类
2. 某一篇文章设置为A类
3. 首页显示这篇文章属于A、B、C三类

（因为我不会php所以不会改）

**Comment by xulouzhe** [comment]
当前版本：v2.2
地址：blog.xlz.pub

**Comment by trinitrotofu** [comment]
@xulouzhe 收到，将马上修复该 Bug，谢谢您的反馈！

**Comment by trinitrotofu** [comment]
@xulouzhe Bug 已修复，请下载新版（2.2.1），对此十分抱歉！

**Comment by xulouzhe** [comment]
谢谢，问题解决了，辛苦了。
你的网站 https://tntofu.com/ 现在好像加载有点问题，css和js加载不出来。

**Comment by xulouzhe** [comment]
我发现我开梯子可以上，是服务器被墙的原因吗

**Comment by xulouzhe** [comment]
现在已经好了
