### ISSUE TITLE
评论框下方出现错误

### ISSUE THREAD

**Issue by Dreaminko** [trinitrotofu/Bubble#22]
评论框下方出现一串错误信息
`, "text/html").getElementsByTagName("script") var script for(var i = 0; i
但是貌似没有影响评论
![image](https://user-images.githubusercontent.com/62631990/89744761-9675fb80-dae2-11ea-9379-0683f362ca5d.png)

**Comment by trinitrotofu** [comment]
@Zhou216 这个不是主题的问题，查看了一下代码，感觉可能是你的 APlayer 插件引起的。

**Comment by Dreaminko** [comment]
那么怎么解决这个问题呢
这导致无法正常评论...但是Aplayer插件对我来说挺有用的

**Comment by trinitrotofu** [comment]
请问您安装的哪个插件？有 github 地址吗？

**Comment by Dreaminko** [comment]
https://github.com/MoePlayer/APlayer-Typecho

**Comment by trinitrotofu** [comment]
实际测试是没问题的。

主题版本：4.0.1

插件版本：2.1.2

插件设置：

![20200810230532](https://user-images.githubusercontent.com/60971116/89797869-0d040f00-db5e-11ea-83ef-a4f843cef0d3.png)

效果：

![](https://user-images.githubusercontent.com/60971116/89797680-cb736400-db5d-11ea-88e5-b972f75e8513.png)

**Comment by Dreaminko** [comment]
我这里所有版本和设置都和您的一样
但还是有这个问题...

**Comment by trinitrotofu** [comment]
请尝试把某些其他插件暂时关掉。

否则我也没什么办法了 QAQ

**Comment by Dreaminko** [comment]
找到原因了
关闭全站pjax即可解决...

**Comment by xulouzhe** [comment]
可是我也挺想要pjax的QAQ

**Comment by trinitrotofu** [comment]
@Zhou216 收到，我会尽快查明原因并尝试修复，谢谢反馈！

**Comment by Rorical** [comment]
问题已解决，请等待下个版本的Release
