### ISSUE TITLE
自定义导航栏

### ISSUE THREAD

**Issue by Dreaminko** [trinitrotofu/Bubble#24]
请问可以做一个自定义导航栏的功能么
现在貌似是自动显示所有页面
这导致了我手气不错的功能无法添加

或者我应该修改主题的哪一部分做到自定义呢？

**Comment by trinitrotofu** [comment]
@Zhou216 实际上本来 4.0.0 版本是准备加入自定义导航栏功能的，但是之前咕咕咕太久了就没加了。
下一个版本更新我加入这个新功能吧。

**Comment by Rorical** [comment]
现在版本 4.0.2 已经加入！
请到设置更新主题吧！
咕咕咕！
