### ISSUE TITLE
主题不支持引用段落样式渲染

### ISSUE THREAD

**Issue by Avimitin** [trinitrotofu/Bubble#25]
文章引用段貌似并不会正常显示，会变成普通字体样式。只能使用引用外部CSS来渲染。

- 原主题

![原主题](https://cdn.jsdelivr.net/gh/Avimitin/PicStorage/pic/20200811144958.png)

- 个人更改

![](https://cdn.jsdelivr.net/gh/Avimitin/PicStorage/pic/20200811145105.png)

![](https://cdn.jsdelivr.net/gh/Avimitin/PicStorage/pic/20200811145206.png)

希望后续更新能补充上完整 Markdown 语法渲染，如果只能使用 HTML 来写文章实在是过于不方便。

**Comment by Avimitin** [comment]
暂时先使用了BBCode 的 Secodary 来替代使用，但是希望能原生支持 Markdown 的 > 引用

**Comment by trinitrotofu** [comment]
@Avimitin 这个其实是 argon design 的锅——它的引用部分和普通段落**几乎**一模一样。

实际上还是有差别的，仔细看 css 代码可以看出 23333

下一个更新我做一下优化吧，这个问题已经被提出过两次了。

**Comment by Avimitin** [comment]
好的，主题很整洁，我很喜欢，加油哦
