### ISSUE TITLE
bbcode没有解析

### ISSUE THREAD

**Issue by Jasonwi** [trinitrotofu/Bubble#26]
typecho version : 1.1 (17.10.30)
theme version : 4.0.1
![Snipaste_2020-08-14_10-49-56](https://user-images.githubusercontent.com/59698185/90226673-e851b500-de45-11ea-8e79-bed6aba4c1a5.png)
已经禁用相关插件
![image](https://user-images.githubusercontent.com/59698185/90226717-fdc6df00-de45-11ea-921d-72a852f379c8.png)
在正文添加后显示如上图 [原链接](http://jland.boke.run/archives/20.html)
另外主题自动更新报错（这可能是因为网站限制了权限？）
![image](https://user-images.githubusercontent.com/59698185/90226833-35ce2200-de46-11ea-86f7-63f9cab870c3.png)

**Comment by Rorical** [comment]
1. 关于BBCode的问题，由于是采用了HTML标签，所以编辑器需要在上下添加三个感叹号来告诉MD解析器“这是HTML，不是Markdown”
2. 主题更新出错，请给予PHP操作目录的权限，具体包括设置.user.ini和文件夹的Permission

**Comment by Rorical** [comment]
感叹号形如
!!!
<bbcode></bbcode>
!!!

**Comment by Jasonwi** [comment]
@Rorical 感谢！
