### ISSUE TITLE
短代码不起作用

### ISSUE THREAD

**Issue by Song-Xin233** [trinitrotofu/Bubble#28]
文档里说可能是第三方插件问题，但是我并没有安装第三方插件，但是依然没有短代码选项，好迷哟
![Screenshot_20200907_232725_com huawei browser](https://user-images.githubusercontent.com/64391901/92402341-fbfcec80-f161-11ea-87dc-aa9bbddd518c.png)
![Screenshot_20200907_232704_com huawei browser](https://user-images.githubusercontent.com/64391901/92402357-ff907380-f161-11ea-8495-55065d5a43ab.jpg)

**Comment by Rorical** [comment]
我不是太明白您说的短代码选项是什么
是bbcode吗？
如果是的话，这玩意没有选项，请参照#26

**Comment by Song-Xin233** [comment]
了解了！感谢大佬的回复！
