### ISSUE TITLE
首页文章如何配置不显示全文

### ISSUE THREAD

**Issue by hrj5032188** [trinitrotofu/Bubble#31]
第一次用typecho，写了一篇三五页的文章，发布后在首页看到这篇文章直接显示了全文，而看您演示的是可以只显示部分的
请问这应该怎么配置？

**Comment by Clouder0** [comment]
https://github.com/trinitrotofu/Bubble/issues/29

**Comment by langonginc** [comment]
@hrj5032188  把 `functions.php` 中的 `printArticle()` 函数中的 `<?php $that->content('') ?>` 换成 `<?php $that->excerpt(你希望显示的字数, '') ?>`

**Comment by ZYLHL** [comment]
```
<!--more-->
```
论养成写摘要的好习惯

**Comment by Rorical** [comment]
解决啦！关了哟！
