### ISSUE TITLE
自定义相应布局无效果

### ISSUE THREAD

**Issue by Keep-Dream** [trinitrotofu/Bubble#4]
需要实现的功能：在屏幕width大于800px时，显示2列。而非一直一列

**Comment by trinitrotofu** [comment]
@Keep-Dream 那样不就是双栏主题了么？
可能主题描述中没说清楚，Bubble 从最初设计上就是单栏主题，工具栏置于页脚处。

**Comment by Keep-Dream** [comment]
行吧。我给个建议。建议给备案信息直接写出预留的位置。这样能少动一点源码。

**Comment by trinitrotofu** [comment]
@Keep-Dream 嗯，谢谢您的建议，我打算直接让页脚文字部分可自定义，简介有效。

**Comment by Keep-Dream** [comment]
另外还有分类是不是有BUG？所有的分类都会显示。而不是只显示你选择的分类

**Comment by trinitrotofu** [comment]
@Keep-Dream 这是一个已知 Bug，并且已在新版（2.2.1）中被修复，您可以更新主题以修复该 Bug。

**Comment by Keep-Dream** [comment]
index文件下的头像img标签拥有背景颜色。我不认为这有用处。当我使用透明头像时，它会携带背景色。建议把头像的背景颜色改为透明。

**Comment by trinitrotofu** [comment]
@Keep-Dream 收到，很不错的建议，谢谢！
