### ISSUE TITLE
友链不显示头像和布局啊，只显示一个友链名称，而且我预览的时候，也是只有一个友链名称。

### ISSUE THREAD

**Issue by NianBroken** [trinitrotofu/Bubble#40]
友链不显示头像和布局啊，只显示一个友链名称，而且我预览的时候，也是只有一个友链名称。

**Comment by asforest** [comment]
是使用bblist+bblink标签包裹的友链吗
另外能提供一下编辑界面的截图吗

**Comment by NianBroken** [comment]
![屏幕截图 2021-05-04 174255](https://user-images.githubusercontent.com/57057288/116986281-2c505700-ad00-11eb-8930-43df8fe01d48.png)
![屏幕截图 2021-05-04 174329](https://user-images.githubusercontent.com/57057288/116986344-412cea80-ad00-11eb-9b54-a45603e5dc0d.png)
就像这样，没用布局没用头像，没用描述，只有一个名称

**Comment by NianBroken** [comment]
> 是使用bblist+bblink标签包裹的友链吗
> 另外能提供一下编辑界面的截图吗
就像这样，没用布局没用头像，没用描述，只有一个名称
![屏幕截图 2021-05-04 174329](https://user-images.githubusercontent.com/57057288/116986716-b698bb00-ad00-11eb-983a-7837fbab4455.png)
![屏幕截图 2021-05-04 174255](https://user-images.githubusercontent.com/57057288/116986726-bac4d880-ad00-11eb-9018-28c6f1cbd477.png)

**Comment by asforest** [comment]
你可以试一下参考这个 issue的解决办法 #26 
尝试使用!!!包裹bblist
```
!!!
<bblist>
<bblink link="https://tntofu.com" icon="https://tntofu.com/usr/uploads/2020/03/4228973783.jpg" des="三硝基豆腐的博客">豆腐蒸锅</bblink>
<bblink link="https://blog.boxpaper.club" icon="https://tntofu.com/usr/uploads/2020/04/2709766458.png" des="/ No Result !">Rorical</bblink>
</bblist>
!!!
```

**Comment by NianBroken** [comment]
> 你可以试一下参考这个 issue的解决办法 #26
> 尝试使用!!!包裹bblist
> 
> ```
> !!!
> <bblist>
> <bblink link="https://tntofu.com" icon="https://tntofu.com/usr/uploads/2020/03/4228973783.jpg" des="三硝基豆腐的博客">豆腐蒸锅</bblink>
> <bblink link="https://blog.boxpaper.club" icon="https://tntofu.com/usr/uploads/2020/04/2709766458.png" des="/ No Result !">Rorical</bblink>
> </bblist>
> !!!
> ```

![屏幕截图 2021-05-04 182626](https://user-images.githubusercontent.com/57057288/116990882-50169b80-ad06-11eb-82fc-05f5ad439eb7.png)
依旧不行

**Comment by asforest** [comment]
我这边测试是没问题的，你是否使用了三方插件进行前端渲染呢，或者也可以看看后台有没有报错信息什么的

![image](https://user-images.githubusercontent.com/28993050/116997428-5e1cea00-ad0f-11eb-9641-9313c50242e8.png)

**Comment by asforest** [comment]
另外你的rewrite可能有问题，正常情况下url里面是没有index.php出现的，我猜想也可能和这个原因有关

**Comment by asforest** [comment]
> > 你可以试一下参考这个 issue的解决办法 #26
> > 尝试使用!!!包裹bblist
> > ```
> > !!!
> > <bblist>
> > <bblink link="https://tntofu.com" icon="https://tntofu.com/usr/uploads/2020/03/4228973783.jpg" des="三硝基豆腐的博客">豆腐蒸锅</bblink>
> > <bblink link="https://blog.boxpaper.club" icon="https://tntofu.com/usr/uploads/2020/04/2709766458.png" des="/ No Result !">Rorical</bblink>
> > </bblist>
> > !!!
> > ```
> 
> ![屏幕截图 2021-05-04 182626](https://user-images.githubusercontent.com/57057288/116990882-50169b80-ad06-11eb-82fc-05f5ad439eb7.png)
> 依旧不行

另外也可以检查一下是不是有css没有加载成功

**Comment by NianBroken** [comment]
上面的问题都解决了，现在新的问题来了，我添加图片之后，点击图片无法放大
文章地址：https://blog.nianbroken.top/archives/108/，点击之后没反应
我 想要下图的那种效果
![屏幕截图 2021-05-05 152629](https://user-images.githubusercontent.com/57057288/117108800-4b112500-adb6-11eb-94f0-b612e773a62a.png)
