### ISSUE TITLE
点击图片之后无法放大

### ISSUE THREAD

**Issue by NianBroken** [trinitrotofu/Bubble#41]
我添加图片之后，点击图片无法放大
文章地址：https://blog.nianbroken.top/archives/108/
点击之后没反应
我想要下图的那种效果
![屏幕截图 2021-05-05 152629](https://user-images.githubusercontent.com/57057288/117109010-962b3800-adb6-11eb-9fff-819c74bd6684.png)

**Comment by asforest** [comment]
将主题设置里的PJAX回调函数中的`myFunction();`删除试试

**Comment by asforest** [comment]
> 我添加图片之后，点击图片无法放大
> 文章地址：https://blog.nianbroken.top/archives/108/
> 点击之后没反应
> 我想要下图的那种效果
> ![屏幕截图 2021-05-05 152629](https://user-images.githubusercontent.com/57057288/117109010-962b3800-adb6-11eb-9fff-819c74bd6684.png)

因为找不到这个函数，导致后续的图片放大相关的代码没有被正常执行

**Comment by NianBroken** [comment]
> > 我添加图片之后，点击图片无法放大
> > 文章地址：https://blog.nianbroken.top/archives/108/
> > 点击之后没反应
> > 我想要下图的那种效果
> > ![屏幕截图 2021-05-05 152629](https://user-images.githubusercontent.com/57057288/117109010-962b3800-adb6-11eb-9fff-819c74bd6684.png)
> 
> 因为找不到这个函数，导致后续的图片放大相关的代码没有被正常执行

好了好了，谢谢谢谢谢谢谢谢

**Comment by asforest** [comment]
不客气
