### ISSUE TITLE
首页的一些问题

### ISSUE THREAD

**Issue by langonginc** [trinitrotofu/Bubble#43]
# 文章列表中的内容奇怪

![2021-05-14_17-16](https://user-images.githubusercontent.com/59787082/118249604-2b75ad00-b4d8-11eb-8412-6c7b1cea0282.png)

字的颜色是蓝色的

# 添加头图之后

![2021-05-14_17-18](https://user-images.githubusercontent.com/59787082/118249890-755e9300-b4d8-11eb-9495-f2ff2034dfea.png)

css 发生变形

PHP74 + Typecho1.1 + Bubble4.0.2

**Comment by Rorical** [comment]
请提供一下网页链接方便排查

**Comment by langonginc** [comment]
https://516wjy.xyz:516

**Comment by langonginc** [comment]
@Rorical 

我目前发现在 `functions.php` 中的 `printAricle()` 函数在打印图片时出现了一些问题：

- CSS class 不存在: `list-image-card`, `list-card-bg`, `list-image-card-section`

也就是说，前端 HTML 无法加载这些 class 所以在打印带有头图的文章时就会出现上述问题。

希望您能检查一下 CSS 的上传问题。谢谢。

**Comment by langonginc** [comment]
@Rorical 

我目前发现在 `functions.php` 中的 `printAricle()` 函数在打印图片时出现了一些问题：

- CSS(`css/main.min.css`) class 不存在: `list-image-card`, `list-card-bg`, `list-image-card-section`

也就是说，前端 HTML 无法加载这些 class 所以在打印带有头图的文章时就会出现上述问题。

希望您能检查一下 CSS 的上传问题。谢谢。

-- UPD --

# 其实就是 `main.min.css` 和 `main.css` 内容不符，完整版的CSS有那些class而min版没有，您可能需要重新min一次

**Comment by langonginc** [comment]
> # 其实就是 `main.min.css` 和 `main.css` 内容不符，完整版的CSS有那些class而min版没有，您可能需要重新min一次

这里我提供一个非常简单的解决方案（适用于用户），将 `header.php` 中 41 行的 min 去掉即：

```html
<link type="text/css" href="<?php $this->options->themeUrl("assets/css/main.css"); ?>" rel="stylesheet">
```

**Comment by langonginc** [comment]
@Rorical 希望作者能通过我的PR！

#46

**Comment by Rorical** [comment]
pr内对main.min.css进行了何种修改？
我经过再次检查，确认现有min.css是压缩过的版本。内容相符。
如果网站出现问题，很可能是缓存等原因造成的。

**Comment by langonginc** [comment]
纯压了，我查看了原来下载的文件，min里面最后并没有 `list-image-*` class

**Comment by langonginc** [comment]
@Rorical 我这边发现所有的样式问题均来自 min 文件的问题，因为我先将 `index.php` 中的第41行引用换成**非**min版，能正常显示，换回min版就不能显示，然后我重新压之后再看就没这个问题了，而且连带着有些字体颜色的问题也解决了。

**Comment by Rorical** [comment]
通过再次对比文件，我认为您提交的文件与现有min.css无很大差异。请您再次检查，因为其他更新的人似乎未遇到此问题

**Comment by langonginc** [comment]
那谢谢您了，可能是我这边哪里出现了问题，目前我已经解决了，那我就关掉这个 issue 和 pr 了。
