### ISSUE TITLE
RSS 无缘无故失效了 QAQ、

### ISSUE THREAD

**Issue by OwO996** [trinitrotofu/Bubble#51]

**Comment by OwO996** [comment]
这个跟主题有关系吗？

**Comment by asforest** [comment]
RRS是Typecho的内置功能，不受主题的影响，可以检查一下有没有插件重新了RRS相关的代码或者覆盖了RRS的路由

**Comment by OwO996** [comment]
> RRS是Typecho的内置功能，不受主题的影响，可以检查一下有没有插件重新了RRS相关的代码或者覆盖了RRS的路由

好的，我去看看，感谢您的回复。

**Comment by OwO996** [comment]
好吧，我安装的插件没有会对 RSS 造成影响的呀。
我安装的插件有：
自带的“hello world”和一个评论自动邮箱通知。

**Comment by asforest** [comment]
访问RRS时，会提示什么具体错误信息吗？比如浏览器的DNS解析错误，或者Typecho的错误之类的

**Comment by OwO996** [comment]
> 访问RRS时，会提示什么具体错误信息吗？比如浏览器的DNS解析错误，或者Typecho的错误之类的

感谢您的回复，麻烦您了。我刚刚看见了 V2EX 上的大佬有说我网站的伪静态设置有问题。。改了下配置后就好了。
麻烦佬了，QAQ。

**Comment by asforest** [comment]
不客气的😄
