### ISSUE TITLE
功能建议: 能加个夜间模式嘛

### ISSUE THREAD

**Issue by Yoorkin** [trinitrotofu/Bubble#6]
如题XD

**Comment by trinitrotofu** [comment]
可以有，不过它的应用场景是什么呢？
似乎不会有多少人在晚上关灯后盯着博客看很久鸭？
（小说阅读站倒确实需要这样的功能，但是我想用 typecho 做小说站的应该……不太多吧？）

**Comment by kerrinz** [comment]
> 可以有，不过它的应用场景是什么呢？
> 似乎不会有多少人在晚上关灯后盯着博客看很久鸭？
> （小说阅读站倒确实需要这样的功能，但是我想用 typecho 做小说站的应该……不太多吧？）

白底黑字看久了眼睛累，还是暗黑模式舒服。
阅读博客文章不仅是自己，也可能还有路人。现在写代码遇到问题去搜索、看文章，太多白底黑字还是有点受不住。
