### ISSUE TITLE
能不能添加一个如图功能

### ISSUE THREAD

**Issue by BaseOrange** [trinitrotofu/Bubble#7]
![S00329-23490029](https://user-images.githubusercontent.com/49298726/77853702-1ed0bf80-7218-11ea-9dd9-ba8e375d8734.jpg)

**Comment by BaseOrange** [comment]
![S00329-23490029](https://user-images.githubusercontent.com/49298726/77853719-360fad00-7218-11ea-9004-880b6ee22f20.jpg)

**Comment by xulouzhe** [comment]
这个好像是需要背景图片的，直接照搬会引起版权问题

**Comment by trinitrotofu** [comment]
@pinkjun 这个功能可以有，但其实设计本主题之初我的想法就是设计一个简单通用的单栏主题，这种功能在更换主题时需要涉及到文章内容的修改，本人并不是很需要这种功能(可能我的想法太简单了吧，哈哈)。不过如果您乐意，您可以实现后提交 pr 为本主题的开发添砖加瓦。

**Comment by trinitrotofu** [comment]
@xulouzhe 另外借个楼，主题昨天更新了备案说明功能，另外背景图片功能也在开发中了，现在已经写好了首页图片功能，具体可以看我的博客。😉

**Comment by BaseOrange** [comment]
> @pinkjun 这个功能可以有，但其实设计本主题之初我的想法就是设计一个简单通用的单栏主题，这种功能在更换主题时需要涉及到文章内容的修改，本人并不是很需要这种功能(可能我的想法太简单了吧，哈哈)。不过如果您乐意，您可以实现后提交 pr 为本主题的开发添砖加瓦。

我有个想法，用CSS和DIV来实现，明天测试下可行不

**Comment by xulouzhe** [comment]
> @xulouzhe 另外借个楼，主题昨天更新了备案说明功能，另外背景图片功能也在开发中了，现在已经写好了首页图片功能，具体可以看我的博客。😉

已更新

**Comment by trinitrotofu** [comment]
> > @pinkjun 这个功能可以有，但其实设计本主题之初我的想法就是设计一个简单通用的单栏主题，这种功能在更换主题时需要涉及到文章内容的修改，本人并不是很需要这种功能(可能我的想法太简单了吧，哈哈)。不过如果您乐意，您可以实现后提交 pr 为本主题的开发添砖加瓦。
> 
> 我有个想法，用CSS和DIV来实现，明天测试下可行不

恩，其实 CSS 部分估计不需要您劳心，我觉得最好是在[argon design 官网](https://demos.creative-tim.com/argon-design-system/)找对应样式

**Comment by BaseOrange** [comment]
我在argon design 官网找到一些样式，然后加在<a>标签上可行，大佬能不能指导一下怎么用在文章里面，比如说在编辑器加个按钮，点一下自动插入，如果大佬有时间的话，希望能，知道一下思路，嘻嘻嘻

**Comment by trinitrotofu** [comment]
@pinkjun typecho 原版编辑器新增按钮估计不好实现，但是您所说的插入`[scode ...][/scode]`这种功能是可以做到的。

不过作者本身很菜，没写过这些东西，但是我觉得思路应该没错，就是用 js 代码做替换，找到含有`[scode]`这样的关键字的文章部分，并把它替换成那些短代码框的 html 标签代码，这样就可以了。

但是正如我之前所说，这样做可能会引起一些 Bug，例如如果人家文章中确实需要输入`[scode]`这个字样，并且不希望你把它变成一个短代码框呢？应该采用什么样的机制避免问题呢？这样也许会变得有些复杂。另外就是这种标签太特殊了，并不是所有主题都通用的，因此用户更换主题时会带来问题，我个人认为这样子会让问题太复杂了。

还有最后一点哦，就是其实 typecho 编辑器是支持插入 html 代码的，如果您需要这个功能，其实可以直接通过插入 html 代码实现。

最后，十分感谢您的建议和贡献，虽然您的建议不一定会被包含在代码中，但是它确实会推动主题的进步，谢谢！

**Comment by trinitrotofu** [comment]
@pinkjun 啊好吧，~~经过严密的讨论~~我们开发者打算实现您所说的这个功能，预计将在下个版本中放出，敬请期待。

**Comment by BaseOrange** [comment]
那就等大佬的操作了，嘻嘻嘻

**Comment by Liupaperbox** [comment]
首先，把这种东西解析为html的话有两种选择，后台php解析和前台js解析。后台解析的原理是参与到Typecho自带markdown解析的过程里，比较稳定也可以避免亿些坑，但是这是插件的职责，主题无法参与到typecho后台的解析中。如果是前台js解析的话，第一点是typecho后台的md解析器会解析中括号，导致中括号消失，第二点是无法判断用户是不是真的想要输入这个标签，可能会不加区分的都解析成html。当然有一些办法能避免，但是太麻烦了，有任何简单的办法嘛？

**Comment by trinitrotofu** [comment]
@pinkjun 已实现
您可以在这里预览该功能：
[https://tntofu.com/archives/94.html](https://tntofu.com/archives/94.html)

**Comment by trinitrotofu** [comment]
@pinkjun 该功能已在 3.0.0 版本中实现，请更新主题以获取该功能。
