### ISSUE TITLE
图片路径问题

### ISSUE THREAD

**Issue by xulouzhe** [trinitrotofu/Bubble#8]
新版本加入了背景图片设置功能，但是我发现我写的路径不对
背景图片为`/usr/themes/Bubble-master/images/` 目录内,
但是我写`images/xxx.jpg`无法显示,
`https://域名/images/xxx.jpg`也无法显示

**Comment by xulouzhe** [comment]
使用`usr/themes/Bubble-master/images/xxx.jpg`就可以了,但是图片有一个变暗效果,请问如何修改

**Comment by xulouzhe** [comment]
变暗好像也无伤大雅

**Comment by xulouzhe** [comment]
发现了一个bug：使用主题自带的设置背景图片时，在404页面会变成紫色背景而非自定义背景

**Comment by trinitrotofu** [comment]
背景图片我才用的方法是作为“关于”页面的附件上传后取图片的绝对路径，这样方便管理。
变暗是特意添加的，为了使标题文字（白色）更加清晰，不受背景图片影响。
如果您觉得不需要变暗，可以通过添加自定义 css 实现：

```css
.shape-image:before {
    background-color: rgba(0,0,0,0);
}
```

其中`rgba()`的第四个参数可以调整变暗程度，范围为 0~1 的实数，0 为完全透明，1 为完全不透明。

**Comment by trinitrotofu** [comment]
> 发现了一个bug：使用主题自带的设置背景图片时，在404页面会变成紫色背景而非自定义背景

完蛋，忘记改了……

十分感谢！

（怎么办难道又要赶紧出一个新的版本？）

头疼啊……

**Comment by xulouzhe** [comment]
悄悄commit一次

**Comment by trinitrotofu** [comment]
@xulouzhe 诶？为什么我的 404 页面没有这个问题呢？

或者说我误会了您的意思？

因为实际上主题的 404 调用的是`archive.php`，是使用了随机头图功能的呀？

**Comment by xulouzhe** [comment]
我只设置了 首页背景图像地址，没有设置 随机背景图像地址，是不是这个原因

**Comment by trinitrotofu** [comment]
嗯对，首页背景和其他页面的背景图是分开的，首页背景是固定的某张图，其他页面的头图是可以随机的。

**Comment by xulouzhe** [comment]
我的[捂脸]

**Comment by trinitrotofu** [comment]
哈哈没事，谢谢反馈啦！

另外您的左下角的备案信息蓝色可能太醒目了，可以给链接的`<a></a>`标签内加入`class="footer-link"`，会让颜色更和谐

**Comment by xulouzhe** [comment]
这可能又是一个bug，没有设置**随机背景图像地址**的时候，除了**首页**以外其他页面背景是紫色。
在设置了**随机背景图像地址**之后，我的**关于页面**背景正常显示，但是其他页面，如**分类页面**、**作者页面**背景会变灰色

**Comment by trinitrotofu** [comment]
@xulouzhe 嗯……我之前说明了首页背景图像和其他页面背景图像设置是相互独立的，也就是首页设置了背景图像后其他页面若没设置随机背景图像将会显示默认紫色背景。

至于第二个问题，这是由于您使用了相对路径的原因，因为分类页面和搜索页面的路径并不是根目录，会导致出现一系列问题，请使用绝对路径。

**Comment by xulouzhe** [comment]
好的(第一句话我只是做个铺垫)

**Comment by trinitrotofu** [comment]
@xulouzhe 包括首页图像也请使用绝对路径，否则翻到第二页就……灰了

**Comment by xulouzhe** [comment]
问题已解决，谢谢大佬！
